FROM php:8.1-fpm

RUN apt update && \
    apt upgrade -y && \
    apt install -y git && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# https://pecl.php.net/package/xdebug
RUN pecl channel-update pecl.php.net && \
    pecl install xdebug-3.1.5 && \
    mkdir -p /var/log/php

EXPOSE 9000
WORKDIR /var/www
CMD composer install
CMD php-fpm
