networks:
  iptv:
    driver: bridge

services:

  php:
    container_name: iptv-php
    env_file:
      - .env
    environment:
      - PHP_IDE_CONFIG=serverName=iptv.local
    build:
      dockerfile: docker/php/${IPTV_ENV}.dockerfile
    restart: unless-stopped
    networks:
      - iptv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/${IPTV_ENV}.php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./log/php:/var/log/php:rw
      - ./src:/var/www:rw
      - ./playlists.ini:/var/www/config/playlists.ini:ro

  nginx:
    container_name: iptv-nginx
    image: nginx:latest
    restart: unless-stopped
    networks:
      - iptv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./log/nginx:/var/log/nginx:rw
      - ./src:/var/www:ro
    ports:
      - '8080:80'
    links:
      - php
    depends_on:
      - php
