networks:
  iptv:
    driver: bridge

services:

  nginx:
    container_name: iptv-nginx
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx:rw
      - ./src/svc-main:/var/www:ro
    ports:
      - ${IPTV_NGNIX_PORT}:80
    links:
      - svc-main
    depends_on:
      - svc-main
    networks:
      - iptv

  keydb:
    container_name: iptv-keydb
    build:
      context: ./docker/keydb/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/keydb/redis.conf:/etc/redis/redis.conf
      - ./docker/keydb/data/:/data:rw
    ports:
      - ${IPTV_KEYDB_PORT}:6379
    networks:
      - iptv

  svc-main:
    container_name: iptv-svc-main
    build:
      context: ./docker/php/
      dockerfile: ${IPTV_ENV}.dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PHP_IDE_CONFIG=serverName=iptv.local
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/${IPTV_ENV}.php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./log/php:/var/log/php:rw
      - ./src/svc-main:/var/www:rw
      - ./commit:/var/www/commit:ro
      - ./playlists.ini:/var/www/playlists.ini:ro
    networks:
      - iptv
